# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Cristiano Isaac
author-title: Database/Data Administrator (DBA/DA)
#gravatar: d36a082aacb53b6f76869748fb4b81d4
email: cristianoisaac@gmail.com
twitter: cristiano_isaac
#github: WendellAdriel
googleplus: +cristianoisaac
#facebook: wendell.adriel.7
linkedin: cristianoisaac/en
bio: "Brazilian Database Administrator. PostgreSQL 8.4/9.X, MySQL 5.X and SQL Server 2012/14.
      I graduated in Computer Engeneering and I'm finishing my graduation in Oracle Database 11g. I work mainly with the following DBMS: 
      SQL Server 2014 with Always-On feature, PostgreSQL 9.X with PostGIS 2.X and MySQL 5.X. 
      I love to learn new skills using them to improve my experience in my work and also with things that are not my responsability, 
      helping my teammates and sharing my knowledge with those who ask.
      I work fully with Database Administrator and Data Administrator since 2013 but was already studying and using it in my work since 2009.
      I prefer to work with Database Administrator but I also like to work with Data Administrator. I've also worked with BI projects using Saiku
      and Pentaho and liked the experience very much."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values

db:
  - name: MySQL 5.X
    level: 5
  - name: PostgreSQL 8.4
    level: 4
  - name: PostgreSQL 9.X
    level: 4
  - name: SQL Server 2012
    level: 3
  - name: SQL Server 2014
    level: 4
  - name: Oracle 11g
    level: 3
  - name: MongoDB
    level: 1
  - name: NoSQL
    level: 1

features:
  - name: PostGIS 2.X feature for PostgreSQL
    level: 3
  - name: Always-On feature for SQL Server
    level: 4

methodologies:
  - name: Agile Methodologies
    level: 2
  - name: Scrum
    level: 2

front-end:
  - name: CSS 3
    level: 3
  - name: JavaScript
    level: 3
  - name: jQuery
    level: 2

back-end:
  - name: PHP
    level: 4
  - name: SQL
    level: 5

others:
  - name: Report Server
    level: 3
  - name: Sharepoint
    level: 2
  - name: Saiku 2.X Standalone
    level: 3
  - name: Pentaho Data Integrator
    level: 5

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap, bourbon]
